
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  timeout: 5000
  password: 1234569
  host: localhost

development:
  <<: *default
  database: recipe_app_development
  username: postgres
  password: 1234569
  host: localhost
  port: 5432

test:
  <<: *default
  database: recipe_app
  username: postgres
  password: 1234569
  host: 127.0.0.1


production:
  <<: *default
  database: recipe_app_production
  